import DashboardIcon from './dashboardIcon.svg';
import LogOut from './logOut.svg';
import LogoAi from './logoAi.svg';
import LogIn from './login.svg';
import JobIcon from './job.svg';
import CompaniesIcon from './companiesIcon.svg';
import SettingIcon from './settingIcon.svg';
import SeekersIcon from './seekers.svg';
import BuildingIcon from './buildingIcon.svg';
import AppIcon from './applicationIcon.svg';
import ApplicationIcon from './applicationIcons.svg';
import GoogleIcon from './googleIcon.svg';
import ResumeIcon from './resumeIcon.svg';
import ActiveCompany from './acitiveCompaniesIcon.svg';
import ActiveApplication from './activeApplicationIcon.svg';
import ActiveDashboard from './activeDashboardIcon.svg';
import ActiveSeeker from './activeSeekerIcon.svg';
import ActiveSetting from './activeSettingIcon.svg';
import ActiveRegister from './activeRegisterIcon.svg';
import JobSeekerIcon from './jobSeekerIcon.svg';
import DeleteIcon from './deleteIcon.svg';
import DocumentIcon from './documentIcon.svg';
import UploadIcon from './uploadIcon.svg';

export { DashboardIcon, LogOut, LogoAi, LogIn, JobIcon, CompaniesIcon, ApplicationIcon, SettingIcon, SeekersIcon, BuildingIcon, AppIcon, GoogleIcon, ResumeIcon, ActiveApplication, ActiveCompany, ActiveDashboard, ActiveSeeker, ActiveSetting, ActiveRegister, JobSeekerIcon, DeleteIcon, DocumentIcon, UploadIcon };
